name: Cifrado

on:
  push:
    branches:
      - workflows5

jobs:
  job1:
    name: 'Mi primer Job'
    runs-on: ubuntu-latest
    steps:
      - name: "Primer step"
        run: |
          echo "${{ secrets.SECRET_1 }}"