name: Fourth
env:
  WORKFLOW_VARIABLE: WorkflowVar
  SCOPE: ScopeVar

on:
  push:
    branches:
      - workflows4

jobs:
  job1:
    name: 'Mi primer Job'
    runs-on: ubuntu-latest
    env:
      JOB_VARIABLE: JobVar
      SCOPE: ScopeVarJobWide
    steps:
      - name: "Primer step"
        env:
          STEP_VARIABLE: StepVar
          SCOPE: ScopeVarStepWide
        run: |
          echo "${{ env.WORKFLOW_VARIABLE }}"
          echo "${{ env.SCOPE }}"
          echo "${{ env.JOB_VARIABLE }}"
          echo "${{ env.STEP_VARIABLE }}"
      - name: "Segundo step"
        run: |
          echo "${{ env.SCOPE }}"
  job2:
    name: "segundo job"
    runs-on: windows-latest
    steps:
      - run: |
          echo "${{ env.SCOPE }}"