name: Third

on:
  push:
    branches:
      - workflow3

jobs:
  job1:
    name: 'Mi primer Job'
    runs-on: ubuntu-latest
    steps:
      - name: 'Primer step'
        uses: actions/checkout@v3
        with:
          repository: jmoyano/eati2023
          ref: main
          path: ./main
      - name: "Segundo step"
        uses: actions/checkout@v3
        with:
          repository: jmoyano/eati2023
          ref: anotherbranch
          path: ./anotherbranch
      - name: "Tercer step"
        run: |
          cat ./main/message.txt
          cat ./anotherbranch/message.txt